#161213 Jennifer Briner
#Discriminability modeling: Convert SPEC output files so they play well with JND comparison script
#-------------------------------------------------

#Goal: compare the spectral sensitivities of different butterfly species/sexes
#Inputs: spreadsheets generated by SPEC

rm(list = ls())

#read in tab delimited SPEC output files
setwd("/home/jbriner/Dropbox/School/UCI/Briscoe/Experiments/DiscriminabilityModeling/MyOutput/KyleDataAsInput/161118_HerMF_NoIrradianceVK")
  herato_f_Kyle.df <- read.delim("3_161118_Herato_fem_contrasts_cells.csv", header=FALSE, sep = "\t")
  herato_m_Kyle.df <- read.delim("3_161118_Herato_male_contrasts_cells.csv", header=FALSE, sep = "\t")

#Remove headers (rows 1-7) and exp. numbers (row 9 and column 2)

  herato_f_Kyle.df <-herato_f_Kyle.df[-c(1:7,9), -2]
  herato_m_Kyle.df <-herato_m_Kyle.df[-c(1:7,9), -2]

  
#Save output to csv 
  #------------------------------
  
  date = Sys.Date()
  
  #write output to csv
    write.csv(x=herato_f_Kyle.df, file=paste("R", "Herato_F_Kyle", sep="_", date)) #manually enter the body of the filename: replace "Herato_F_Kyle". Change x to df.
    write.csv(x=herato_m_Kyle.df, file=paste("R", "Herato_M_Kyle", sep="_", date)) 